### ISSUE TITLE
decomposition lab

### ISSUE THREAD

**Issue by EstevahnAguilera** [comp129/comp55#100]
In general, I had struggled in the beginning with Java and with Gobjects. I instead looked for alternatives and found this helpful website and it specified different methods that were very helpful. In this case, I believe that it would be beneficial for future students as well who are struggling just like I did. This is the link[ ](https://cs.stanford.edu/people/eroberts/jtf/javadoc/student/acm/graphics/GObject.html#:~:text=move(double%20dx%2C%20double%20dy,displacements%20given%20in%20polar%20coordinates.)

**Comment by onzfonz** [comment]
You can link to this but you would need to provide some background as well.
It can't just be a link, there would need to be context.

**Comment by EstevahnAguilera** [comment]
Okay I will add background content as well!
