### ISSUE TITLE
Lists.md: Enhance Explanation of ArrayList Limitations with Primitive Types

### ISSUE THREAD

**Issue by Abdullah0x0** [comp129/comp55#105]
The current section on `ArrayList` limitations with primitive types (e.g., `int`, `double`) could be enhanced for better clarity and understanding. The original text states:

> The other drawback is that they don't work directly with primitives like `int` and `double`. To use primitives as lists it is a little bit more cumbersome. To create an `ArrayList` of `int`s, we have to use an object type called `Integer`. After doing so, Java will then take the integers and magically box them into `Integer` objects that simply contain the number.

While this provides a basic overview, it lacks a detailed explanation that could help readers understand the underlying concepts more thoroughly and could confuse beginners. A revised version could include:

- A more explicit explanation of why `ArrayList` cannot directly handle primitive types, emphasizing the object-oriented nature of collections in Java.
- A clearer introduction to wrapper classes (`Integer`, `Double`, etc.) and their role in enabling `ArrayList` to store primitive values.
- A brief introduction to autoboxing and unboxing processes, illustrating how Java automatically converts between primitive types and their corresponding wrapper classes when working with collections.
- An example demonstrating how to declare and use an `ArrayList<Integer>` to store `int` values, highlighting the seamless nature of autoboxing and unboxing in practical use.
- Additionally, providing a link for further reading on autoboxing and unboxing.
https://www.geeksforgeeks.org/autoboxing-unboxing-java/

This fix would clarify a potentially confusing topic for beginners and also add to the document's educational value by offering a more comprehensive understanding of how Java collections work with primitive types.

**Comment by onzfonz** [comment]
This is fine and you can start working on this.

However, we will not reference SEO content (geeksforgeeks is one of these SEO style sites), so you'll need to find something that is more official on the topic (or at least something that is not purely devoted to serving ads)
