### ISSUE TITLE
ACM.md Proposal: Easier to Understand for newcomers

### ISSUE THREAD

**Issue by MichaelJr1** [comp129/comp55#107]
**1. My proposals is to edit this image by replacing it with the same code and adding comments to it.**
I noticed that the explanation for each line of the code is below the whole thing. This is fine for referencing in the future , but comments on each line can help students understand what each line's purpose is in the code.

    import acm.graphics.*;
    import acm.program.*;
    import acm.util.*;
    import java.awt.*;
    
    public class ACMLab extends GraphicsProgram {
        public static final int PROGRAM_HEIGHT = 600;
        public static final int PROGRAM_WIDTH = 800;
    
        public void init() {
            setSize(PROGRAM_WIDTH, PROGRAM_HEIGHT);
            requestFocus();
        }
    
        public void run() {
            add(new GLabel("Hello World", 300, 300));
        }
    
        public static void main(String[] args) {
            new ACMLab().start();
        }
    }

**Comment by onzfonz** [comment]
ok, let's see if that'll work, but you should also have another sentence that talks about how you shouldn't write code with this many comments and that they are only here for this intro lab

**Comment by MichaelJr1** [comment]
I'll make that clear. 👍
