### ISSUE TITLE
#109 Add Detailed Instructions for Removing Java on Windows and MacOS

### ISSUE THREAD

**Issue by duongnguyen130** [comp129/comp55#109]
As a student who just started my second semester when I was taking COMP 55, I did not know how to navigate through window or macOS file system. 
What we are having: "1. Visiting your add and remove programs setting in windows (or applications on a mac)"
**Solution: **
We need to add detailed instructions on how to remove Java from both Windows and MacOS systems. 
These instructions will guide students through the process step-by-step.

**Comment by onzfonz** [comment]
Sounds good!  Looking forward to seeing it!
