### ISSUE TITLE
6-Lists: Add link that compares Arrays and ArrayLists

### ISSUE THREAD

**Issue by marissam27** [comp129/comp55#13]
Adding a link in the Introduction section that compares Arrays and ArrayLists can help students understand the differences and be able to decide on which to use in different situations in the future. This link (https://www.geeksforgeeks.org/array-vs-arraylist-in-java/) shows code examples along with explaining their differences in various categories, such as length, size, and dimensionality.

**Comment by onzfonz** [comment]
We won't use geeksforgeeks
I'm ok with another link to another place, but it would have to be from a more reputable source, not from one that is merely playing the Search Engine Optimization game
So you would need to do something else and also cite that other one, but you can work on it

**Comment by onzfonz** [comment]
let's use this instead:
https://www.w3schools.blog/difference-between-array-and-arraylist-in-java
it's a simple table
