### ISSUE TITLE
13-Refact: Mention adding comments for complicated code

### ISSUE THREAD

**Issue by WCBauer** [comp129/comp55#14]
In the section talking about removing if statements, I noticed a couple of the examples ended up with code that was more difficult to understand. While complexity is briefly mentioned when the ternary operator is brought up, I think it would be productive to include a sentence or two about adding descriptive comments where code isn't super clear in how it works.

**Comment by onzfonz** [comment]
I think that's fair, just be warned there may be some revisions of that statement, but go for it!
Also be on the lookout with issue #5
