### ISSUE TITLE
12 - Hash Part 1 doesn't mention potential get() usages

### ISSUE THREAD

**Issue by Jabez-J-Lee** [comp129/comp55#2]
I noticed that the Basic HashMap Usage doesn't mention that the get function can also be used to get a key from a definition. While although this might not be a common usage, it could be something that student's aren't entirely aware of from simply reading the markdown.

**Comment by onzfonz** [comment]
So, for this, I'll let you go ahead and propose something, but also make sure that you propose why something like that would be useful, like to come up with an example on when that would be useful in their context
If you cannot think of a good reason, then it would be better to think of another change to do.
