### ISSUE TITLE
JavavsCPP: Add missing '+' to table comparing two images

### ISSUE THREAD

**Issue by Kaung-Sone** [comp129/comp55#20]
In the table with the two images comparing C++ and Java, the title for the C++ image is missing a '+'. I think this should be fixed for aesthetic purposes.  
![image](https://user-images.githubusercontent.com/72995175/223592244-11b92965-842f-4c6f-bb03-499014eff9d0.png)

**Comment by onzfonz** [comment]
OK, and can you also look for one more fix or add a sentence that discusses C++ vs Java or to potentially look for other pictures?

**Comment by Kaung-Sone** [comment]
Could I talk about passing variables into functions? C++ allows passing by value or passing by reference, while Java allows only passing by value. This could go after the section about pointer notations.
