### ISSUE TITLE
adding extra link for more info

### ISSUE THREAD

**Issue by gafur55** [comp129/comp55#22]
The website Lucid Chart is very handy in creating uml diagrams. There are a lot of functionalities there which can be easily done by dragging different objects. I would like to add that to the end of the page as an extra/useful tool if someone is interested to see.
I can also a add a small tutorial which will teach them how to set it up and will make them familiar with the tools there

**Comment by onzfonz** [comment]
I think we are going to stick to plantUML, since it's not a bad language to get to learn more of...are you looking at the UML diagrams one?
If you were to add a link to lucid chart, you would have to add rationale for why they would still be expected to use plantuml.  Can you reference which file you would do this in?

**Comment by onzfonz** [comment]
make sure it's in the one of the three UML ones

**Comment by onzfonz** [comment]
Also isn't lucidchart a pay only option or like super limited free option?
I would rather you say that it's popular but that we won't use it and again for some of the reasons provided

**Comment by gafur55** [comment]
I was thinking to add it to the 65-UMLclass.md 
It has a free option and a specific one for the uml diagrams. This is the link I was talking about: 
https://lucid.app/lucidchart/146e78ff-8d20-4018-8b3d-4529e249068e/edit?beaconFlowId=DECD419160D0D5DE&page=0_0&invitationId=inv_06e96c1d-fa9c-4556-8936-3315f901dd04#

**Comment by gafur55** [comment]
![image](https://user-images.githubusercontent.com/101157079/223862958-6bdf453e-bae1-4a2d-8432-6b94339eb3b7.png)
it is something like that. 
If I remember correctly, I have done this tutorial.  UML would be better in a sense that with writing the code design gets easier and faster. I can add it like for the future projects or some other reasons, this can be using in both for uml and also there are other many type of diagrams can be used. If this works, please, let me know so I can make some changes. Thanks!

**Comment by onzfonz** [comment]
yes, I think you could just mention it as something that can be done in the future if you really need to, but plantuml will surpass any of those limitations and will lead to something that can be easily modified later.
I would really have you make the case for this as like "yes this is an option and yes it's popular, but plantuml once we get the syntax can work really well for us!"
I mean the other thing about it is that we can check in plantuml into git much more easily as well!
