### ISSUE TITLE
Adding link to provide more detail/examples in regards to UML Diagrams

### ISSUE THREAD

**Issue by jafernoorani** [comp129/comp55#23]
In order to assist students with UML Diagrams (in case they have not used them before). I added a link to a guide of example UML Diagrams to look at. This website is very handy when it comes learning about UML types. It event gives various types of examples, and gives them real world examples for how UML Diagrams can look based upon the type of tool you are trying to create. I would like to add this link after the bolded section titled, "Drawing a class in UML on a piece of paper".

https://creately.com/blog/diagrams/uml-diagram-types-examples/

Here is the link for reference!

**Comment by onzfonz** [comment]
If you look at the rest of the lab, it starts to discuss the components.
The site you linked provides types for all different kinds of UML diagrams, and while a survey may be handy, I'm not sure this is the right place for it.

I honestly think that perhaps linking directly to plantuml's documentation may be better.
I'm going to let you continue, but realize that it may take several revisions for this to actually go somewhere with it
