### ISSUE TITLE
4-ACM: Add instructions for how to add the ACM.jar to your buildpath

### ISSUE THREAD

**Issue by erodriguez4620** [comp129/comp55#24]
In the current instructions, there I did not see anything which mentioned the addition of the `acm.jar` to the build path. From my understanding, not having this in the build path will not allow you to use the ACM library, which is important for this lab.
This issue will involve showing the user how to install the jar while also supplying a link to it.

**Comment by onzfonz** [comment]
The reason for this not being there is that they are provided with the jar from the starting resources, which unfortunately aren't shown
The project already has the acm.jar
You could do a separate page that gives these instructions though as like a common issues in COMP 55 Page (almost like a FAQ, but with the general things that keep happening)
We'll then find a way to link it later

**Comment by erodriguez4620** [comment]
![20230309_003217](https://user-images.githubusercontent.com/72991689/223967170-8119d305-4c50-4b69-856d-7e1578db9335.gif)
