### ISSUE TITLE
Add extra information section with useful links in 5-Interact.md

### ISSUE THREAD

**Issue by AdilHajiyev** [comp129/comp55#25]
I just want to add some links to other websites that give extra info about different events and listeners that might be helpful for the students. I plan make extra section on the bottom of the page and add these links.

**Comment by onzfonz** [comment]
So fyi #21 is already placing some of this information in the timers lab.
Most of the interactivity lab is geared toward getting them ready for traffic jam's dragging.
I think if you create another page in a supplemental folder, let's put the changes in there for now

**Comment by AdilHajiyev** [comment]
So if I understood right, I need to make another file and put the links there?
