### ISSUE TITLE
61-UseCasePic: Add link to UML website and provide more examples

### ISSUE THREAD

**Issue by Amr-mah** [comp129/comp55#26]
The document briefly explains what a UML is but it would be more helpful to provide more information on UML by adding a link to the UML website: https://www.uml.org/
Additionally, it would be helpful to provide more examples on how use case diagrams are used in software development. By giving examples on the benefit of use case diagrams in real work settings, students will understand the value of it.

**Comment by onzfonz** [comment]
I think that's fair, but please make sure it is geared towards Use Case Diagrams, or to provide a very brief overview in a separate section that talks about how we'll be going over three different types of diagrams in the course.

**Comment by onzfonz** [comment]
the examples you can concentrate on just coming up with one for now if you'd like
