### ISSUE TITLE
Quick Reference for Understanding and Using Eclipse - Adding eclipse keyboard shortcuts

### ISSUE THREAD

**Issue by AlihaNaeem** [comp129/comp55#3]
A cool resource to add to this lab would be adding a table of keyboard shortcuts for eclipse for both Mac and Windows and I would like to make that addition to this document

**Comment by onzfonz** [comment]
There are actually a lot of keyboard shortcuts mentioned throughout the different labs...
See here

https://github.com/search?q=repo%3Acomp129%2Fcomp55%20keyboard&type=code

Perhaps coming up with a table in the [EclipseLoot](https://github.com/comp129/comp55/blob/bede07da19b24d91763dcbda8277e02459210e66/docs/labs/EclipseLoot.md?plain=1#L63) document and doing a better job of linking that together with Understanding and Using Eclipse would be good?

If you are up for doing this, go ahead and move forward, or propose further details here

**Comment by AlihaNaeem** [comment]
The eclipseloot document will have a table of keyboard shortcuts for navigating eclipse
