### ISSUE TITLE
14-test.md needs an update to the, Assertions and GUI (optional) 

### ISSUE THREAD

**Issue by ClintPenafiel** [comp129/comp55#30]
In the Assertions and GUI (optional) category of the 14-test.md file, it gives a link for an optional guide created by former COMP 55 students and when it is clicked it goes to a 404 Page not found window. This part of the lab could be updated to remove the part of optional guide, update the link if the guide does exist somewhere or I can add a resource that can help students know more about GUI testing.

**Comment by onzfonz** [comment]
Yes, that works!
