### ISSUE TITLE
Include the Timer class link in Timer.md

### ISSUE THREAD

**Issue by Alan007-hub** [comp129/comp55#32]
https://docs.oracle.com/javase/7/docs/api/javax/swing/Timer.html

I think this will provide the student an in-depth explanations and functions if they wish to learn more about timer class.

**Comment by onzfonz** [comment]
Where would this go with regards to the timer lab?
Why would it be java api 7?
Might make sense to think slightly more about where this would be, but I'll do the rocket in case you want to get started (but realize there may be more back and forth here)

**Comment by Alan007-hub** [comment]
Hello Professor, 
I am going to update it for java 8 api as COMP 055 uses java 8 sdk. **https://docs.oracle.com/javase/8/docs/api/javax/swing/Timer.html**
As for the placement of the link, I would like to place it at the end of three step checklist reference.
