### ISSUE TITLE
65-UML Class Diagram Lab | Suggest having more visuals

### ISSUE THREAD

**Issue by evanvang** [comp129/comp55#33]
I think in this page it does a lot to explain what a UML is and its purposes but doesn't really go to show a student how exactly one could be structured and how one could look like when completed. A better explanation could be not only showing the micro but macro side of a UML and how it essentially gives the student a blueprint of how their program may be structured. Overall I wouldn't say this is a huge game changer but just gives a bit more clarification on UML's as I remember I had a hard time grasping them up until I had completed one myself.

**Comment by evanvang** [comment]
I want to make it more easily understood by adding visuals and showing connections between diagrams and other additional things to supplement better/quicker learning

**Comment by onzfonz** [comment]
I'm ok with this but please make sure to coordinate with #23 and #35
