### ISSUE TITLE
Updated link potentially needed in Debug.md

### ISSUE THREAD

**Issue by bayers1** [comp129/comp55#39]
In the "The Debugging Lab" section of the file, one of the first lines gives mention to reutilizing the import functionality of a previous lab. However, the link to said lab simply results in a 404 error. An ideal fix to this would be to instead have the link redirect the user to image2.gif within the media files of lab2media, which would in turn repurpose the link into more of a refresher for the user in case they couldn't remember how to do so.

**Comment by onzfonz** [comment]
Can you be more specific on which line it is.
And are you referring to this file?
https://comp129.github.io/comp55/labs/3-Debug.html#some-advice-when-debugging
Remember to look at it through the website instead

**Comment by bayers1** [comment]
It was the very beginning of the paragraph for the “The Debugging Lab” section. However, having tried the link again, it does appear to actually work, so there actually is no issue.
