### ISSUE TITLE
4-ACM: Add links to helpful summary pages for the differnt ACM Classes

### ISSUE THREAD

**Issue by Alex-Hum** [comp129/comp55#4]
I think in the ACM Lab it'd be good to add some extra resources for students to reference either during the lab or after the lab when they're doing their own ACM implementations. The https://cs.stanford.edu site has a lot of summary pages that give full, detailed information about the various ACM Classes' constructors, available methods, and usages that I think would be a good addition.

Also, probably not as helpful as the suggestion I gave above, but I think also adding a small snippet of example code for implementing a GImage in Java--just to provide visual aid for those that learn better from visual examples.

**Comment by onzfonz** [comment]
I think perhaps linking to them as you are going along so like introducing links using the [] and () syntax over words to create links would be good!

So like you could link [like this instead](http://cs.stanford.edu)
