### ISSUE TITLE
Timer Lab | Suggest having visual representation of the Timer class

### ISSUE THREAD

**Issue by EthanDonley** [comp129/comp55#46]
Under the Timer Lab for the" What is a Timer" section, its actual explanation is relatively barebones (repeating alarm) as eventhough it explains what the Timer class is EXACTLY, it's hard to see why it would be used in the context of code to many people who don't understand timers.  Due to how important Timers are when it comes to making games it would be useful to have a visual on EXACTLY what the timer does in the context of a game or program (Think Mario Bros and Mario moving to the right via a timer)

**Comment by onzfonz** [comment]
ok, so you are proposing making an image or something?  Sounds good
