### ISSUE TITLE
Edit to token generation section of 8-Github-Prep.md

### ISSUE THREAD

**Issue by bayers1** [comp129/comp55#49]
Within the section "I have the URL but have yet to connect to GitHub", the file explains how to generate a token, but appears to leave out the crucial point that the generated token will no longer be viewable after the user has left the generation page, which was an issue that I myself encountered. I believe that including this detail, likely bolded, will better ensure that the user is more careful of how they go about securing their token.

**Comment by onzfonz** [comment]
looks good!
