### ISSUE TITLE
13-Refact: Fix code blocks to display correctly

### ISSUE THREAD

**Issue by DeanShin** [comp129/comp55#5]
The code blocks in 13-Refact sections 3. and 4. are not displaying correctly, and are hard to read. We should fix these to be code blocks or images to be more legible for users. Furthermore, by putting these, and other code blocks into a Java code block, we can add syntax highlighting.

<img width="1027" alt="Screen Shot 2023-03-03 at 12 56 24 PM" src="https://user-images.githubusercontent.com/42852604/222827811-1924e4ed-4e78-4487-8b0c-188425f0c739.png">

**Comment by onzfonz** [comment]
yeah, so in github markdown it does not render correctly, but it does do a better job in Jekyll once you go to the actual github pages site

<https://onzfonz.github.io/comp55/labs/13-Refact.html#5-use-variables-to-help-you-refactor-code>

![image](https://user-images.githubusercontent.com/239024/222869372-73766fe8-67f2-43fe-b835-09b68041f21c.png)

I don't think Jekyll does syntax highlighting just yet unless we do a custom flavor of it that we deploy as well, which would require getting Ruby setup on your system and specifying a different markdown editor

**Comment by onzfonz** [comment]
there are still some things to fix there though so that would be the way to go

**Comment by DeanShin** [comment]
Gotcha, I can do an overall clean-up of 13. I think the syntax highlighting will still work though, given this screenshot
<img width="1060" alt="Screen Shot 2023-03-03 at 6 01 40 PM" src="https://user-images.githubusercontent.com/42852604/222869897-d29b0781-8561-4d89-be21-1d8a6bd8d5a1.png">

**Comment by DeanShin** [comment]
Syntax highlighting doesn't work in tables unfortunately, but cleaned it up otherwise
