### ISSUE TITLE
Sequence Diagram Mini-Lab adding images to fit the examples

### ISSUE THREAD

**Issue by nfantinodyer** [comp129/comp55#52]
For me it's hard to imagine some of the plantUML code, so I think adding images to the steps could be helpful. Giving an example of an alt output could be helpful to add at the end.

**Comment by onzfonz** [comment]
So part of the reason that we don't have this is that providing a picture is the end result of following the instructions, wouldn't it encourage the students to just create that picture?

Have you done this lab before when you took COMP 55?
If not, I would have you walk through it first and see if it makes sense

**Comment by onzfonz** [comment]
Also, @L0Pope would not be the one that would need to give you the rocket emoji, I would need to do so

**Comment by nfantinodyer** [comment]
![Screenshot 2023-03-09 185227](https://user-images.githubusercontent.com/89417141/224211275-678cd734-8fa5-4253-a137-90142880a2db.png)
![umlcode](https://user-images.githubusercontent.com/89417141/224211491-67eec9f5-470d-46ba-aeb6-be524800ceb2.png)

I was thinking something more along these lines. This is just going by the base example that you provided and not making a unique UML. 

And as for the alt text I was just thinking of providing an image and not the code to get there:
![altuml](https://user-images.githubusercontent.com/89417141/224211602-3d457b55-b3cb-45be-ab69-a6fb780e1f46.png)

**Comment by onzfonz** [comment]
OK as long as it's not the solution then go ahead and propose it
