### ISSUE TITLE
JavavsCPP.md - lacking explanation 

### ISSUE THREAD

**Issue by paneta3757** [comp129/comp55#64]
In the section explaining why Java doesn't have pointer notation could use some external sources to explain why. It might help clarify as to why it doesn't have it and could be a better example than showing the code.

**Comment by onzfonz** [comment]
Instead of pointing to a resource, I would be ok with this but you would also need to make sure that you have some initial easy to understand explanation or why the external resource would be needed.

**Comment by onzfonz** [comment]
@paneta3757 if you are ok with that addendum, I will place it with the 🚀
