### ISSUE TITLE
EclipseLoot: Add Images Or Gifs For Closing/Removing/Quitting section of EclipseLoot

### ISSUE THREAD

**Issue by 1KAG** [comp129/comp55#65]
This section seems clear of any images/gifs in sight:

![Screenshot 2024-03-01 220601](https://github.com/comp129/comp55/assets/148159945/477ff612-0f16-4e96-9102-6f1420a12c4e)

I believe if I add a couple of images/gifs for this section would help one dramatically since having knowledge of Closing/Removing/Quittingise is a key to using Eclipse. In addition, adding images will help users understand and effectively use Eclipse without any issues.

**Comment by onzfonz** [comment]
yeah looks good!
But make sure to add a sentence or two or something else that helps link the images to what is being said
