### ISSUE TITLE
GitTips.md - Missing visual example

### ISSUE THREAD

**Issue by YJSong30** [comp129/comp55#66]
On the fourth tip under GitTips.md, it would be helpful to add a visual example. This was something I struggled with when I was learning git for the first time because I wasn't in a project setting. When there are conflicting merges it would show you which lines were conflicting. Attached is an example of that.

![Egit-0 10-merge-conflict](https://github.com/comp129/comp55/assets/76021136/504ee6bf-7e1a-4879-87d5-17ad58e4bb42)

**Comment by onzfonz** [comment]
sure, that works!
