### ISSUE TITLE
9-Github.md no images/gifs to show how to pull from Git

### ISSUE THREAD

**Issue by Daniel89987** [comp129/comp55#67]
In Github.md, there are many images and gifs depicting the various steps. However, when it comes to pulling, there are only a few lines of text describing how you can pull, with no visual representation. I think it would help a lot if I can add at least an image to show how you can find the correct "pull" option

**Comment by onzfonz** [comment]
You can do this, but make sure to add a sentence or two or something else that helps link the images to what is being said, or to state how the animation will help.
