### ISSUE TITLE
67-Sequence.md - Include example and images

### ISSUE THREAD

**Issue by JohnP105** [comp129/comp55#73]
Problem Description:
- The Sequence Diagram Mini-Lab provides detailed instructions on creating sequence diagrams using PlantUML. However, it lacks concrete examples to illustrate the concepts effectively. 

Solution:
- I recommend adding examples to the lab instructions such as sample sequence diagrams or code snippets demonstrating the concepts discussed.  I would also add images of what it would look like in PlantUML if we were to put in the example code.

**Comment by onzfonz** [comment]
yup sounds like a good idea!
