### ISSUE TITLE
9-Github.md Lack of crucial background information before the actual lab starts 

### ISSUE THREAD

**Issue by layupmisser** [comp129/comp55#75]
Problem:
Lack of crucial background information before the actual lab starts 

Specifically recall doing this lab one year ago during COMP55 and being extremely confused at what was going on. It would only be one year later when I did a Codecademy course on how repositories and Git actually works did I truly become proficient at using Git and actually come to see its benefit and why it's so universally used in the industry. I even started using Git and Github for all of my future school and personal projects, even when it wasn't even a requirement. 

Solution:
To solve this issue of the lab, a video for Codecademy should be that showcase is what git stage, git commit, and git push all do. There should also be an explanation on local and remote repositories. Etc. 

If there was already a lecture talking about this right before the lab, the video should still be included because at the very least it would serve as an excellent recap of everything that was taught. Also since it's a video, the student could watch and learn the content at their own pace to truly acquire the knowledge at hand.

Result:
With this background information put into place, future students could probably extract far more from this lab since they can map the practical knowledge they acquire from this lab to their of Git and GitHub.

**Comment by onzfonz** [comment]
I think your idea of what git stage, git commit and git push all do, as well as remote vs local or some further git theory could be something to write something about, either before, after or during the lab (you could do like little pieces to map the practical parts with what is happening theoretically.

Perhaps if you did this it could be like what is happening in step 7, but with less text or maybe some intro just before they need to pick teams or something like that.
(This could also happen with git prep mini lab as well, or a separate doc)

> ***Side Note:*** While videos are nice and often engaging, studies have shown that people tend to overestimate what they learn from videos and that the learning equivalency is about the same as compared to text.  (Happy to provide resources, but see Tarchi, Zaccoletti & Mason's article from 2021)
Text is easier to edit as well.

**Comment by layupmisser** [comment]
So just to clarify, you just want me to explain it in text and forget about the video?

**Comment by onzfonz** [comment]
> So just to clarify, you just want me to explain it in text and forget about the video? 

Yep!
