### ISSUE TITLE
8-Github-Prep.md update Image for generating a token  

### ISSUE THREAD

**Issue by fernalga** [comp129/comp55#76]
Issue:
Currently the below image is outdated, along with this are the steps listed which should also be updated. Now when generating a token, there are two options to pick from. Fine-grained tokens (Beta) and Tokens (classic). Upon first time experience with GitHub it isn't obvious that Tokens (classic) is what should be clicked, and even further when you click Generate new token, the user is given two options again. Generate new token (beta) & Generate new token (classic). None of these are brought up and can lead to misdirection. 

![image](https://github.com/comp129/comp55/assets/148602612/fee3d95c-bfa2-4a98-9ed6-d2844e368851)

Solution:
These steps should be updated to match with the current layout of GitHub, and the Image, should either be a gif displaying what to click or an updated Image of the current look of Git so future students can match their screen with an accurate representation for the lab.

**Comment by onzfonz** [comment]
ok, I like it!
