### ISSUE TITLE
GitTips.md near 4 and 5

### ISSUE THREAD

**Issue by K5741** [comp129/comp55#77]
In comp 55, my team constantly had the issue when we pulled, and pushed a few, or one of us would not have a working project even when it was exactly the same as the working person's work. So another tip for if your project is not working after a pull try the following steps :
1. Gradle > Refresh Gradle
2. Build Path > Use as Source Folder
3. Commit and make sure all unstaged are dragged to staged changes. Commit and push

**Comment by onzfonz** [comment]
ok, good, just put an explanation there and I think that will work!
