### ISSUE TITLE
5-Interact.md add more clarification to the exclusivity of the actions performed with the if statement in Lab 5 in the Mouse Event Parameter section

### ISSUE THREAD

**Issue by sthornton04** [comp129/comp55#78]
When completing this lab, I remember I had a large issue because I was not aware that the ball should be moved upward if and only if the mouse was not touching the ball and currently changing the color. I'd like to make additions to the 5-Interact.md file to make this more clear.

**Comment by onzfonz** [comment]
sounds good!  Looking forward to seeing it!
