### ISSUE TITLE
10-Timer.md including some example code clarity and added sample code

### ISSUE THREAD

**Issue by natung15** [comp129/comp55#79]
Issues:
In Step 2 of the lab there could be added images or sample code for setting up the action listener interface and actionPerformed method in the class. Another thing to add is more clarity on objectToBeWokenUp. This is because I remember being confused on what to implement in the spot of objectToBeWokenUp especially in step 3 where you would call the timer's start method where it shows objectToBeWokenUp instead of "this" so some clarity or adjustments on this aspect would be good.

**Comment by onzfonz** [comment]
Sounds good!
