### ISSUE TITLE
13-Refact: Adding link for DeMorgan's laws and fixing the incorrect bold in "Refactoring Lab Directions" section.

### ISSUE THREAD

**Issue by Yupeng-P** [comp129/comp55#8]
Adding a link about DeMorgan's laws can be helpful for students to better understand the negations.

<img width="799" alt="Screen Shot 2023-03-04 at 1 35 59 PM" src="https://user-images.githubusercontent.com/79814523/222929666-196dd112-4406-4394-8991-45633488ce71.png">

In the bottom of the file, there is incorrectly implementation of markdown file syntax, so the context didn't be bold as the expected. It need a small fix.
<img width="1029" alt="Screen Shot 2023-03-04 at 1 40 01 PM" src="https://user-images.githubusercontent.com/79814523/222929786-49670a6e-5ade-4eb4-8449-e85cc9ec6f86.png">

**Comment by onzfonz** [comment]
Ok sounds good!
