### ISSUE TITLE
EclipseLoot.md - adding controls alternatives for Mac users

### ISSUE THREAD

**Issue by 0nkn** [comp129/comp55#81]
I learned that I do not use enough keyboard shortcuts as I should! Since there is a portion of the Eclipse Loot document that provides several shortcuts for Mac, I would like go through the document and add more Mac-related shortcuts to lines where shortcuts do not work with the same exact keys.

For instance, the writer has said, "You can right-click and then say Source->Correct Indentation to fix the indentation. Alternatively, you can also just Select All (Ctrl-A) and then hit Ctrl-I to fix all the indentation, so your code is properly indented at all times." For Mac, you would have to use the command key instead of control (Command + A, Command + I). Mentioning this would eliminate confusion for Eclipse users, say, if they suddenly can't indent anything with Control + I. They wouldn't have to go in and customize all of their own shortcuts.

**Comment by onzfonz** [comment]
Yes, that looks good!
