### ISSUE TITLE
New Page For Teaching Figma

### ISSUE THREAD

**Issue by codythefennec** [comp129/comp55#85]
# Overview
During the previous project one of my teammates used the free website called [Figma](https://www.figma.com/) where he was able to layout all the UI designs.

After he finished creating the UI, implementing them into our project was such an easy task to do that I was astounded with this technique and I feel it should be shared.

In order to share it I would like to create a lab to teach new Comp 55 students how to navigate figma, and lay out their UI for implementation within Comp 55 projects.
# Additional Details
This lab will intend to cover:
- Creating a [figma](https://www.figma.com/) account
- Navigating the home page to create a new project
- Adding in a few elements and laying out objects
- Adjusting properties of objects
- Exporting images and or porting objects into an ACM project
- Additional steps someone may take to do more with figma.
- Cover drawbacks of figma to ACM and what to avoid
# Media
I will intend to add media to help students navigate the website, as I found following gifs from previous labs it made it much easier to understand and do it myself.
I also will intend to write much of the text to be step-by-step and as readable as possible to fit in with the previous labs.

**Comment by onzfonz** [comment]
If you really want to show them this, I would be fine with it, but realize that this is bigger than what is needed for this project, as you are writing a lab.  This would also become like a supplementary lab, so it may end up being linked to from a current lab.  But I'll go ahead and approve
