### ISSUE TITLE
10-Timer.md Bonus#1: 

### ISSUE THREAD

**Issue by rthao1** [comp129/comp55#86]
The idea given in bonus example 1 of lab 10/timers lab was to update the player's current score until they have lost. It was discussed that it can be updated in actionPerformed and to add checks to see if the player has lost. Reading the explanation is a little confusing. An idea to add is to create snippets of sample code/examples for the person doing the lab to see. 
2-3 examples can be provided:
1.a) How to update/code string in actionPerformed that displays score.
1.b) How to count player score/kills. It can be an extra sentence in the instructions that tell the person doing the lab that an integer can be updated near the function used to remove enemies from the screen upon collision.
2) What function to use to check player loss, but leave where to place code to the person doing the lab.

**Comment by onzfonz** [comment]
ok, I'm good with this!
