### ISSUE TITLE
61-UseCasePic.md

### ISSUE THREAD

**Issue by TylerTruong24** [comp129/comp55#87]
Issues: In UML Intro, an example image of a Use Case Diagram should be made with PlantUML under "For a more concrete example of how UML is used in software development, consider the following use case." It would help students visualize what a Use Case Diagram would look like. This will also help students in the lab know if their diagrams are current in the sense of looks.

**Comment by onzfonz** [comment]
sounds good, but I'm also going to want you to add some sentence or something that helps describe or give the picture some context.
