### ISSUE TITLE
GitTips Addition

### ISSUE THREAD

**Issue by esamra** [comp129/comp55#91]
I do like some of the stuff in the git tips but during our project when we did not have the referenced libraries, I had to find how to add the acm jar by myself. I took me a lot of time and youtube videos to find that out. So I can show how to add the acm jar file and I also wanted to add a comparsion chart such as if people wanted to use git commands, I can show them the basics and compare them to the github commands such as git log, git commit, and other git commands. I could make a chart.

**Comment by onzfonz** [comment]
Looks good!
