### ISSUE TITLE
7-Interface.md needs to emphasise the importance of interfaces better.

### ISSUE THREAD

**Issue by AlexDavis47** [comp129/comp55#93]
While going through the interfaces lab for the first time, I remember being sorta confused on what makes them different than inheritance and why they would be used. In my actual Java programs interfaces ended up being invaluable and constantly used. Some additional information on how interfaces can be used to achieve powerful effects in programs could be an improvement.

**Comment by onzfonz** [comment]
ok, that sounds good to me!
